apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: sokos-trekk
  namespace: okonomi
  labels:
    team: okonomi
spec:
  groups:
    - name: sokos-trekk-alerts
      rules:
        - alert: sokos-trekk er nede
          expr: kube_deployment_status_replicas_available{deployment="sokos-trekk"} == 0
          for: 2m
          annotations:
            action: "Sjekk hvorfor applikasjonen er nede"
            summary: "{{ $labels.deployment }} er nede i namespace {{ $labels.namespace }}"
          labels:
            namespace: okonomi
            severity: critical
            sokos_trekk_type: sokos-trekk
            alert_type: custom

        - alert: sokos-trekk har restartet flere ganger de siste 5 minuttene!
          expr: sum(increase(kube_pod_container_status_restarts_total{container=~"sokos-trekk"}[5m])) by (container) > 2
          for: 2m
          annotations:
            action: "Sjekk hvorfor applikasjonen ikke klarer å restarte"
            summary: "{{ $labels.container }} restarter mange ganger"
          labels:
            namespace: okonomi
            severity: critical
            sokos_trekk_type: sokos-trekk
            alert_type: custom

        - alert: Applikasjonen logger høy andel errors
          expr:
            'sum(max_over_time(log_messages_errors{namespace="okonomi",app="sokos-trekk",level="Error"}[5m])
              or vector(0)) -
              sum(max_over_time(log_messages_errors{namespace="okonomi",app="sokos-trekk",level="Error"}[5m]
              offset 5m) or vector(0)) > 0'
          for: 2m
          annotations:
            action: "<https://logs.adeo.no/app/discover#/?_g=(time:(from:now-1d,to:now))&_a=(filters:!((query:(match_phrase:(application:'sokos-trekk'))),(query:(match_phrase:(cluster:'prod-fss'))),(query:(match_phrase:(level:'Error')))))|Sjekk error loggene i sokos-trekk>"
            summary: "`kubectl logs -l app=sokos-trekk -n okonomi` for logger"
          labels:
            namespace: okonomi
            severity: danger
            sokos_trekk_type: sokos-trekk
            alert_type: custom

---


apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: sokos-trekk-slack
  namespace: okonomi
  labels:
    alertmanagerConfig: sokos-trekk-slack
spec:
  receivers:
    - name: sokos-trekk-receiver
      slackConfigs:
        - apiURL:
            key: apiUrl
            name: slack-webhook
          channel: '#team-mob-alerts-prod'
          iconEmoji: ':alert:'
          username: 'Alert prod-fss (sokos-trekk)'
          sendResolved: false
          httpConfig:
            proxyUrl: http://webproxy.nais:8088
          title: |-
            [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }}
          text: >-
            {{ range .Alerts }}
            {{ if or .Annotations.summary .Annotations.message }}
            {{ or .Annotations.summary .Annotations.message }}
            {{ println " " }}
            {{- end }}
            {{- if .Annotations.action }}
            • *action*: {{ .Annotations.action }} {{ println " " }}
            {{- end }}
            {{ end }}
  route:
    groupBy:
      - alertname
    matchers:
      - name: "sokos_trekk_type"
        matchType: "="
        value: "sokos-trekk"
    groupInterval: 10s
    groupWait: 5s
    receiver: sokos-trekk-receiver
    repeatInterval: 10m
