kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: trekk
  namespace: q3
  labels:
    team: okonomi
spec:
  env:
  - name: MQGATEWAY01_HOSTNAME
    value: b27apvl170.preprod.local
  - name: MQGATEWAY01_PORT
    value: "1413"
  - name: MQGATEWAY01_NAME
    value: MQXLSC01
  - name: TREKK_CHANNEL_QUEUEMANAGER
    value: mq://b27apvl170.preprod.local:1413/MQXLSC01
  - name: TREKK_CHANNEL_NAME
    value: Q3_TREKK
  - name: TREKK_TREKK_INN_QUEUENAME
    value: QA.Q3_TREKK.TREKK_INN
  - name: TREKK_TREKK_INN_QUEUEMANAGER
    value: mq://b27apvl170.preprod.local:1413/MQXLSC01
  - name: TREKK_TREKK_INN_BOQ_QUEUENAME
    value: Q3_TREKK.TREKK_INN_BOQ
  - name: TREKK_TREKK_INN_BOQ_QUEUEMANAGER
    value: mq://b27apvl170.preprod.local:1413/MQXLSC01
  - name: OB04_TREKK_REPLY_QUEUENAME
    value: QA.Q3_231.OB04_TREKK_REPLY
  - name: OB04_TREKK_REPLY_BATCH_QUEUENAME
    value: QA.Q3_231.OB04_TREKK_REPLY_BATCH
  - name: SRVTREKK_USERNAME
    value: srvtrekk
  - name: SECURITYTOKENSERVICE_URL
    value: https://sts-q3.preprod.local/SecurityTokenServiceProvider/
  - name: VIRKSOMHET_YTELSEVEDTAK_V1_ENDPOINTURL
    value: https://arena-q1.adeo.no/ail_ws/YtelseVedtak_v1
  image: repo.adeo.no:5443/okonomi/trekk:14.0.12-T
  ingresses:
  - https://trekk-q3.nais.preprod.local
  liveness:
    path: /isAlive
    initialDelay: 30
    periodSeconds: 5
    failureThreshold: 30
  prometheus:
    enabled: true
    path: /prometheus
  readiness:
    path: /isReady
    initialDelay: 30
    periodSeconds: 5
    failureThreshold: 30
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      cpu: "1"
      memory: 1024Mi
    requests:
      cpu: 100m
      memory: 256Mi
  vault:
    enabled: true
    paths:
    - kvPath: /serviceuser/data/dev/srvtrekk
      mountPath: /var/run/secrets/nais.io/srvtrekk
#    - kvPath: /kv/preprod/fss/trekk/default
#      mountPath: /var/run/secrets/nais.io/vault
