kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: trekk
  namespace: default
  labels:
    team: okonomi
spec:
  env:
  - name: MQGATEWAY01_PORT
    value: "1414"
  - name: MQGATEWAY01_NAME
    value: MPLSC01
  - name: MQGATEWAY01_HOSTNAME
    value: a01apvl061.adeo.no
  - name: TREKK_CHANNEL_QUEUEMANAGER
    value: mq://a01apvl061.adeo.no:1414/MPLSC01
  - name: TREKK_CHANNEL_NAME
    value: P_TREKK
  - name: TREKK_TREKK_INN_QUEUENAME
    value: QA.P_TREKK.TREKK_INN
  - name: TREKK_TREKK_INN_QUEUEMANAGER
    value: mq://a01apvl061.adeo.no:1414/MPLSC01
  - name: TREKK_TREKK_INN_BOQ_QUEUEMANAGER
    value: mq://a01apvl061.adeo.no:1414/MPLSC01
  - name: TREKK_TREKK_INN_BOQ_QUEUENAME
    value: QA.P_TREKK.TREKK_INN_BOQ
  - name: OB04_TREKK_REPLY_QUEUENAME
    value: QA.P231.OB04_TREKK_REPLY
  - name: OB04_TREKK_REPLY_BATCH_QUEUENAME
    value: QA.P231.OB04_TREKK_REPLY_BATCH
  - name: SRVTREKK_USERNAME
    value: srvtrekk
  - name: SECURITYTOKENSERVICE_URL
    value: https://sts.adeo.no/SecurityTokenServiceProvider/
  - name: VIRKSOMHET_YTELSEVEDTAK_V1_ENDPOINTURL
    value: https://arena.adeo.no/ail_ws/YtelseVedtak_v1
  image: repo.adeo.no:5443/okonomi/trekk:14.0.12
  ingresses:
  - https://trekk.nais.adeo.no
  liveness:
    path: /isAlive
    initialDelay: 30
    periodSeconds: 5
    failureThreshold: 30
  prometheus:
    enabled: true
    path: /prometheus
  readiness:
    path: /isReady
    initialDelay: 30
    periodSeconds: 5
    failureThreshold: 30
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      cpu: "1"
      memory: 1024Mi
    requests:
      cpu: 100m
      memory: 256Mi
  vault:
    enabled: true
    paths:
    - kvPath: /serviceuser/data/prod/srvtrekk
      mountPath: /var/run/secrets/nais.io/srvtrekk
#    - kvPath: /kv/prod/fss/trekk/default
#      mountPath: /var/run/secrets/nais.io/vault
