apiVersion: "nais.io/v1alpha1"
kind: "Application"

metadata:
  name: sokos-trekk-qx
  namespace: okonomi
  labels:
    team: okonomi
spec:
  image: {{image}}
  port: 8080
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 75
  liveness:
    path: /internal/isAlive
    initialDelay: 5
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/isReady
    initialDelay: 5
    periodSeconds: 5
    timeout: 5
  resources:
    limits:
      memory: 1024Mi
    requests:
      cpu: 500m
      memory: 1024Mi
  ingresses:
    - https://sokos-trekk-qx.intern.dev.nav.no
  prometheus:
    enabled: true
    path: /internal/metrics
  secureLogs:
    enabled: true
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
  azure:
    application:
      enabled: true
      allowAllUsers: true
  accessPolicy:
    inbound:
      rules:
        - application: azure-token-generator
          namespace: nais
          cluster: dev-gcp
  webproxy: true
  envFrom:
    - secret: sokos-trekk-serviceuser-credentials

  env:
    - name: USE_AUTHENTICATION
      value: "false"

    # MQ
    - name: MQ_HOSTNAME
      value: b27apvl219.preprod.local
    - name: MQ_PORT
      value: "1413"
    - name: MQ_QUEUE_MANAGER_NAME
      value: MQLS01
    - name: MQ_CHANNEL_NAME
      value: QX_TREKK
    - name: MQ_TREKK_INN_QUEUE_NAME
      value: QA.QX_TREKK.TREKK_INN
    - name: MQ_TREKK_INN_BOQ_QUEUE_NAME
      value: QA.QX_TREKK.TREKK_INN_BOQ
    - name: MQ_TREKK_REPLY_QUEUE_NAME
      value: QA.QX_231.OB04_TREKK_REPLY
    - name: MQ_TREKK_REPLY_BATCH_QUEUE_NAME
      value: QA.QX_231.OB04_TREKK_REPLY_BATCH
    - name: MQ_LISTENER_ENABLED
      value: "true"

    # SOQP
    - name: SECURITY_TOKENSERVICE_URL
      value: https://sts-q3.preprod.local/SecurityTokenServiceProvider/
    - name: VIRKSOMHET_YTELSEVEDTAK_V1_ENDPOINTURL
      value: https://arena-q0.adeo.no/ail_ws/YtelseVedtak_v1
