apiVersion: "nais.io/v1alpha1"
kind: "Application"

metadata:
  name: sokos-trekk-test
  namespace: okonomi
  labels:
    team: okonomi
spec:
  image: "{{{ image }}}"
  port: 8080
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 75
  liveness:
    path: /internal/isAlive
    initialDelay: 5
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/isReady
    initialDelay: 5
    periodSeconds: 5
    timeout: 5
  resources:
    limits:
      memory: 2024Mi
    requests:
      cpu: 500m
      memory: 1024Mi
  ingresses:
    - https://trekk-test.dev.intern.nav.no
  prometheus:
    enabled: true
    path: /actuator/prometheus
  secureLogs:
    enabled: true
  azure:
    application:
      enabled: true
      allowAllUsers: true
  accessPolicy:
    inbound:
      rules:
        - application: azure-token-generator
          namespace: aura
          cluster: dev-gcp
  webproxy: true
  vault:
    enabled: true

  env:
    - name: USE_AUTHENTICATION
      value: "true"

    # MQ
    - name: MQ_HOSTNAME
      value: b27apvl219.preprod.local
    - name: MQ_PORT
      value: "1413"
    - name: MQ_QUEUE_MANAGER_NAME
      value: MQLS01
    - name: MQ_CHANNEL_NAME
      value: Q1_TREKK
    - name: MQ_TREKK_INN_QUEUE_NAME
      value: QA.Q1_TREKK.TREKK_INN
    - name: MQ_TREKK_INN_BOQ_QUEUE_NAME
      value: Q1_TREKK.TREKK_INN_BOQ
    - name: MQ_TREKK_REPLY_QUEUE_NAME
      value: QA.Q1_231.OB04_TREKK_REPLY
    - name: MQ_TREKK_REPLY_BATCH_QUEUE_NAME
      value: QA.Q1_231.OB04_TREKK_REPLY_BATCH
    - name: MQ_LISTENER_ENABLED
      value: "true"

    # SOQP
    - name: SECURITY_TOKENSERVICE_URL
      value: https://sts-q1.preprod.local/SecurityTokenServiceProvider/
    - name: VIRKSOMHET_YTELSEVEDTAK_V1_ENDPOINTURL
      value: https://arena-q1.adeo.no/ail_ws/YtelseVedtak_v1
