apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sokos-trekk-qx-wiremock
  namespace: okonomi
  labels:
    team: okonomi
spec:
  image: {{image}}
  replicas:
    min: 1
    max: 1
  port: 8080
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 512Mi
  ingresses:
    - https://sokos-trekk-wiremock-qx.intern.dev.nav.no
  accessPolicy:
    inbound:
      rules:
        - application: sokos-trekk-qx