apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sokos-trekk-qx-wiremock
  namespace: okonomi
  labels:
    team: okonomi
spec:
  image: {{image}}
  replicas:
    min: 1
    max: 1
  port: 8080
  resources:
    limits:
      cpu: 1000m
      memory: 1000Mi
    requests:
      cpu: 500m
      memory: 500Mi
  service:
    port: 8080
    protocol: wiremock
  accessPolicy:
    inbound:
      rules:
        - application: sokos-trekk-qx