applicationName: '@project.artifactId@'
applicationVersion: '@project.version@'
bootstrapVersion: '@bootstrap.version@'

info:
  app:
    name: '@project.artifactId@'
    description: '@project.description@'
    version: '@project.version@'

trekk:
  jms:
    concurrentConsumers: 1
    transactionTimeout: 300
  aggregator:
    completionTimeout: 5000 #millisekunder
    completionSize: 10

server:
  port: 8080
  forward-headers-strategy: native

logging:
  config: classpath:logback-spring.xml

management:
  endpoints:
    web:
      exposure:
        include: prometheus

srvappserver:
  username: srvappserver
