server:
  port: 8082

MQGATEWAY01_HOSTNAME: 'e26apvl121.test.local'
MQGATEWAY01_PORT: 1411
MQGATEWAY01_NAME: 'MUXLSC01'
TREKK_CHANNEL_QUEUEMANAGER: 'mq://e26apvl121.test.local:1411/MUXLSC01'
TREKK_CHANNEL_NAME: 'U1_TREKK'
TREKK_TREKK_INN_QUEUENAME: 'QA.U1_TREKK.TREKK_INN'
TREKK_TREKK_INN_QUEUEMANAGER: 'mq://e26apvl121.test.local:1411/MUXLSC01'
TREKK_TREKK_REPLY_QUEUENAME: 'QA.U1_TREKK.TREKK_REPLY'
TREKK_TREKK_REPLY_QUEUEMANAGER: 'mq://e26apvl121.test.local:1411/MUXLSC01'