server:
  port: 8082
NAIS_NAMESPACE: 't8'
NAV_TRUSTSTORE_PASSWORD: '467792be15c4a8807681fd2d5c9c1748'
NAV_TRUSTSTORE_KEYSTOREALIAS: 'na'
NAV_TRUSTSTORE_PATH: '/var/run/secrets/naisd.io/nav_truststore_path'
MQGATEWAY01_HOSTNAME: 'd26apvl257.test.local'
MQGATEWAY01_PORT: '1412'
MQGATEWAY01_NAME: 'MTXLSC01'
TREKK_CHANNEL_QUEUEMANAGER: 'mq://d26apvl257.test.local:1412/MTXLSC01'
TREKK_CHANNEL_NAME: 'T8_TREKK'
TREKK_TREKK_INN_QUEUENAME: 'QA.T8_TREKK.TREKK_INN'
TREKK_TREKK_INN_QUEUEMANAGER: 'mq://d26apvl257.test.local:1412/MTXLSC01'
TREKK_TREKK_INN_BOQ_QUEUENAME: 'T8_TREKK.TREKK_INN_BOQ'
TREKK_TREKK_INN_BOQ_QUEUEMANAGER: 'mq://d26apvl257.test.local:1412/MTXLSC01'
OB04_TREKK_REPLY_QUEUENAME: 'QA.T8_231.OB04_TREKK_REPLY'
OB04_TREKK_REPLY_BATCH_QUEUENAME: 'QA.T8_231.OB04_TREKK_REPLY_BATCH'
SRVTREKK_PASSWORD: 'MRQ60GP3KGssxDY'
SRVTREKK_USERNAME: 'srvtrekk'
SRVTREKK_CERT_PASSWORD: 'oMnihSlw85'
SRVTREKK_CERT_KEYSTOREALIAS: 'app-key'
SRVTREKK_CERT_KEYSTORE: '/var/run/secrets/naisd.io/srvtrekk_cert_keystore'
SECURITYTOKENSERVICE_URL: 'https://sts-t8.test.local/SecurityTokenServiceProvider/'
VIRKSOMHET_YTELSEVEDTAK_V1_SECURITYTOKEN: 'SAML'
VIRKSOMHET_YTELSEVEDTAK_V1_ENDPOINTURL: 'https://arena-t8.adeo.no/ail_ws/YtelseVedtak_v1'
VIRKSOMHET_YTELSEVEDTAK_V1_WSDLURL: 'http://maven.adeo.no/nexus/content/repositories/public/no/nav/tjenester/nav-ytelseVedtak-v1-tjenestespesifikasjon/1.0.1/nav-ytelseVedtak-v1-tjenestespesifikasjon-1.0.1.zip'
