name: Deploy application

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - 'LICENCE'
      - 'CODEOWNERS'
      - '.gitignore'
      - '.editorconfig'
      - 'setupLocalEnvironment.sh'
      - 'dokumentasjon/**'
      - '.github/workflows/build-pr.yaml'
      - '.github/workflows/manual-deploy-dev.yaml'
      - '.github/workflows/manual-deploy-dev-qx.yaml'
      - '.github/workflows/security.yaml'
      - '.github/workflows/alerts.yaml'
      - '.nais/alerts-dev.yaml'
      - '.nais/alerts-prod.yaml'
      - '.github/dependabot.yaml'

env:
  TZ: Europe/Oslo

permissions:
  contents: "write"
  id-token: "write"

jobs:
  build:
    name: Build/test & push image
    uses: navikt/mob-gha-workflows/.github/workflows/gradle-build-push-image.yaml@main
    secrets: inherit

  deploy-dev:
    needs: build
    name: Deploy to dev-fss
    uses: navikt/mob-gha-workflows/.github/workflows/nais-app-deploy.yaml@main
    with:
      cluster: dev-fss
      resource: .nais/naiserator-dev.yaml
      image: ${{ needs.build.outputs.image }}

  deploy-qx:
    needs: [build, deploy-dev]
    name: Deploy to dev-fss-qx
    uses: navikt/mob-gha-workflows/.github/workflows/nais-app-deploy.yaml@main
    with:
      cluster: dev-fss
      resource: .nais/naiserator-qx.yaml
      image: ${{ needs.build.outputs.image }}
  deploy-wiremock-qx:
    needs: [build, deploy-dev]
    name: Deploy wiremock to dev-fss-qx
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 'Deploy to dev-fss'
        uses: nais/deploy/actions/deploy@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CLUSTER: dev-fss
          TEAM: okonomi
          RESOURCE: ".nais/wiremock.yaml"

  deploy-prod:
    needs: [build, deploy-dev, deploy-qx]
    name: Deploy to prod-fss
    uses: navikt/mob-gha-workflows/.github/workflows/nais-app-deploy.yaml@main
    with:
      cluster: prod-fss
      resource: .nais/naiserator-prod.yaml
      image: ${{ needs.build.outputs.image }}
