name: Deploy application manual to dev

on:
  workflow_dispatch:
    inputs:
      java-version:
        required: false
        type: string
        description: Java version to build with
        default: '8'
      environment:
        description: "Environment to deploy to (q1, qx, test)"
        required: true
        type: choice
        options:
          - q1
          - qx
          - test

env:
  TZ: Europe/Oslo

permissions:
  contents: "write"
  id-token: "write"

jobs:
  build:
    name: Build/test & push image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: ${{ inputs.java-version }}

      - name: mvn package
        run: mvn package

      - name: Push Docker Image to GAR
        uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: okonomi
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          tag: ${{ inputs.image-tag }}
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}


  deploy-dev:
    needs: build
    name: Deploy ${{ inputs.environment }} to dev-fss
    if: github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: nais/deploy/actions/deploy@v2
        env:
          IMAGE: ${{ needs.build.outputs.image }}
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-fss
          RESOURCE: .nais/naiserator-${{ inputs.environment }}.yaml
          TIMEOUT: 10m
          PRINT_PAYLOAD: true